services:
    #Observar
    egpv_admin.doctrine_observer:
        class: Nte\Admin\PainelBundle\EventListener\DoctrineEventListener
        arguments: ['@service_container']
        tags:
           # - { name: doctrine.event_listener, event: postUpdate }
          - { name: doctrine.event_listener, event: postPersist }
          - { name: doctrine.event_listener, event: prePersist }
