security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_GERENCIAL, ROLE_AVALIADOR, ROLE_ADMIN_USER, ROLE_ADMIN_EDITAL, ROLE_SUPORTE, ROLE_ADMIN_ARQUIVO]
        ROLE_SUPORTE:     [ROLE_ADMIN]
        ROLE_ADMIN_USER:  ROLE_COLABORADOR
        ROLE_AVALIADOR:   ROLE_COLABORADOR
        ROLE_ADMIN_EDITAL:   ROLE_COLABORADOR
        ROLE_ADMIN_ARQUIVO:   ROLE_COLABORADOR
        ROLE_GERENCIAL:         ROLE_COLABORADOR
        ROLE_COLABORADOR: ROLE_USER


    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        oauth_token:
            logout_on_user_change: true
            pattern: ^/oauth/v2/token
            anonymous: true

        api:
            logout_on_user_change: true
            pattern: ^/app/api
            fos_oauth: true
            stateless: true
            anonymous: false

        main:
            access_denied_url: /candidato
            switch_user: { role: ROLE_ADMIN }
            logout_on_user_change: true
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/app/register, role: ROLE_ADMIN }
        - { path: ^/app/recuperar-senha, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/app/primeiro-acesso, role: ROLE_USER }
        - { path: ^/app/arquivo/, role: ROLE_USER }
        - { path: ^/app/, role: ROLE_COLABORADOR }
        - { path: ^/candidato/, role: ROLE_USER }
