nte_usuario_index:
    path:  /
    defaults: { _controller: NteUsuarioBundle:Usuario:index }

nte_usuario_teste:
    path:  /teste
    defaults: { _controller: NteUsuarioBundle:Usuario:teste }


nte_usuario_perfil:
    path:  /perfil/{id}
    defaults: { _controller: NteUsuarioBundle:Usuario:perfil, id: null }

nte_usuario_editar:
    path:  /editar/{id}
    defaults: { _controller: NteUsuarioBundle:Usuario:editar }

nte_usuario_ativar:
    path:  /ativar/{id}
    defaults: { _controller: NteUsuarioBundle:Usuario:ativar }

nte_usuario_update:
    path:  /atualizar/{id}
    defaults: { _controller: NteUsuarioBundle:Usuario:update }

nte_usuario_novo:
    path:  /novo
    defaults: { _controller: NteUsuarioBundle:Usuario:novo }
