parameters:
    nte_usuario.usuario.handler.class: Nte\UsuarioBundle\Handler\UsuarioHandler
    nte_usuario.usuario.class: Nte\UsuarioBundle\Entity\Usuario

services:
    nte_usuario.login_listener:
        class: 'Nte\UsuarioBundle\EventListener\LoginListener'
        arguments: ['@router', '@event_dispatcher','@security.authorization_checker']
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login', method: onSecurityInteractiveLogin}

    nte_usuario.requests_listener:
        class: 'Nte\UsuarioBundle\EventListener\RequestListener'
        arguments:
                - '@security.token_storage'
                - '@router'
                - '@security.authorization_checker'
        tags:
                - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }




